version: '3.1'

services:
  webserver:
    image: 'cloudwaysdev/ansiblexenial'
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys
    networks:
      xenial_nw:
        ipv4_address: 172.5.0.2
  appserver:
    image: 'cloudwaysdev/ansiblexenial'
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys
    networks:
      xenial_nw:
        ipv4_address: 172.5.0.3
  dbserver:
    image: 'cloudwaysdev/ansiblexenial'
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys
    networks:
      xenial_nw:
        ipv4_address: 172.5.0.4

networks:
  xenial_nw:
    external:
      name: ansible_nw

  